from enum import StrEnum


class MessageEvent(StrEnum):
    INIT_PROFILE = 'INIT_PROFILE'
    USER_ANSWER = 'USER_ANSWER'
    ASSISTANT_QUESTION = 'ASSISTANT_QUESTION'
    PROFILE_COMPLETE = 'PROFILE_COMPLETE'
