from enum import StrEnum


class MessageEvent(StrEnum):
    INIT_PROFILE = 'INIT_PROFILE'
    USER_ANSWER = 'USER_ANSWER'
    ASSISTANT_QUESTION = 'ASSISTANT_QUESTION'
    PROFILE_COMPLETE = 'PROFILE_COMPLETE'
    MAX_REPLIES_REACHED = 'MAX_REPLIES_REACHED'
    PENDING_GENERATION = 'PENDING_GENERATION'


class MessageStatus(StrEnum):
    SUCCESS = 'SUCCESS'
    ERROR = 'ERROR'
